# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [pull_request, push]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: checkout repository
        uses: actions/checkout@v6
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v6
      - name: setup jdk
        uses: actions/setup-java@v5
        with:
          java-version: '25'
          distribution: 'microsoft'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: download modified Baritone
        run: |
          mkdir -p "$GITHUB_WORKSPACE/.deps"

          curl --fail --location --retry 3 \
            "https://github.com/HackerRouter/baritone/releases/download/v26.1.1-hr.1/baritone-api-fabric-26.1.1-hr.1.jar" \
            --output "$GITHUB_WORKSPACE/.deps/baritone-api-fabric.jar"

          echo "182BC016CDDADB339A6CD5B8514CC4C84586A786C440630A125FC519C3E266E8  $GITHUB_WORKSPACE/.deps/baritone-api-fabric.jar" \
            | sha256sum --check
      - name: build
        run: |
          ./gradlew build \
            -Pbaritone_jar="$GITHUB_WORKSPACE/.deps/baritone-api-fabric.jar"
      - name: capture build artifacts
        uses: actions/upload-artifact@v7
        with:
          name: Artifacts
          path: build/libs/
